spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/yourdb
    username: your_username
    password: your_password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none # Wyłącz automatyczne tworzenie tabeli przez Hibernate
    show-sql: true
    properties:
      hibernate.format_sql: true