ldap:
  url: ldap://your-ldap-server:389
  base: dc=example,dc=com
  userDn: cn=admin,dc=example,dc=com
  password: admin-password

# Other Spring Boot configurations can be added below
server:
  port: 8080
