openapi: 3.0.0
info:
  title: Moje API
  version: 1.0.0
paths:
  /example-endpoint:
    get:
      summary: Pobierz listę obiektów
      responses:
        '200':
          description: Sukces
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExampleObject'
              x-table:
                columns:
                  - name: Nazwa
                    type: string
                  - age: Wiek
                    type: integer
                  # Dodaj inne kolumny według potrzeb
components:
  schemas:
    ExampleObject:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
        # Dodaj inne właściwości według potrzeb
